global:
  # scrape_interval:     15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
  external_labels:
      monitor: 'aggregator-test'

scrape_configs:
  - job_name: 'monitoring-prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'process_exporter'
    static_configs:
      - targets: ['localhost:9256']
    metric_relabel_configs:
      - source_labels: ["groupname"]  # the label which needs to be filtered
        regex: "(.*);(.*)"            # the regex to find the expected match
        target_label: "processname"   # add a new label
        replacement: "$1"             # substitute with the 1st match
      - source_labels: ["groupname"]  # the label which needs to be filtered
        regex: "(.*);(.*)"            # the regex to find the expected match
        target_label: "username"      # add a new label
        replacement: "$2"             # substitute with the 2nd match

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['localhost:9100']
